<?php

namespace MCA\CategoriaBundle\Repository;

/**
 * ProdutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdutoRepository extends \Doctrine\ORM\EntityRepository
{
}
