<?php

namespace MCA\CategoriaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProdutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdutoRepository extends EntityRepository
{
}
