index:
    path:  /
    defaults: { _controller: CategoriaBundle:Default:index }
    
categorias:
    path:  /categorias
    defaults: { _controller: CategoriaBundle:Default:index }

categoria_nomeproduto:
    path: /categorias/{nomeCategoria}/{nomeProduto}
    defaults: {_controller: CategoriaBundle:Default:categorias}
    
categoria_categoria:
    resource: "@CategoriaBundle/Resources/config/routing/categoria.yml"
    prefix:   /categoria
    
categoria_produto:
    resource: "@CategoriaBundle/Resources/config/routing/produto.yml"
    prefix:   /produto